# Docker Compose file for PHP, MySQL and PHPMyAdmin
# Version 0.1 
# Date: 2024-12-19

services:
  web:
    image: php:8.2-apache
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html         # Changed from . to ./php
      - ./php.ini:/usr/local/etc/php/php.ini
    environment:
      - PHP_DISPLAY_ERRORS=1
      - PHP_ERROR_REPORTING=E_ALL
      - APACHE_DOCUMENT_ROOT=/var/www/html
    command: >
      bash -c "
        docker-php-ext-install pdo pdo_mysql && 
        a2enmod rewrite &&
        apache2-foreground"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: studentpass
      MYSQL_DATABASE: php_course
      MYSQL_USER: student
      MYSQL_PASSWORD: student
    volumes:
      - ./mysql_data:/var/lib/mysql      # Local directory for MySQL data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: studentpass
      UPLOAD_LIMIT: 64M
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped